apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haalsamachar-auth
  template:
    metadata:
      labels:
        app: haalsamachar-auth
    spec:
      containers:
        - name: haalsamachar-auth
          image: akashsingh04/haalsamachar-auth:5e386bb1438e58cb923f10276e419f64fc46ff74latest
          ports:
            - containerPort: 8084
