apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haalsamachar-blogs
  template:
    metadata:
      labels:
        app: haalsamachar-blogs
    spec:
      containers:
        - name: haalsamachar-blogs
          image: akashsingh04/haalsamachar-blogs:5e386bb1438e58cb923f10276e419f64fc46ff74
          ports:
            - containerPort: 8082
