apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haalsamachar-frontend
  template:
    metadata:
      labels:
        app: haalsamachar-frontend
    spec:
      containers:
        - name: haalsamachar-frontend
          image: akashsingh04/haalsamachar-frontend:518ae8b975bca98b5fe8c0c834c3a85df7f52928
          ports:
            - containerPort: 3000
