apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haalsamachar-graph
  template:
    metadata:
      labels:
        app: haalsamachar-graph
    spec:
      containers:
        - name: haalsamachar-graph
          image: akashsingh04/haalsamachar-graph:5e386bb1438e58cb923f10276e419f64fc46ff74
          ports:
            - containerPort: 4000
