apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haalsamachar-users
  template:
    metadata:
      labels:
        app: haalsamachar-users
    spec:
      containers:
        - name: haalsamachar-users
          image: akashsingh04/haalsamachar-users:5e386bb1438e58cb923f10276e419f64fc46ff74
          ports:
            - containerPort: 8081
